### ISSUE TITLE
Double-clicking associated parkobj creates new instance instead of tab

### ISSUE THREAD

**Issue by Richard-L** [danielmeinert/objectcreator#11]
When you have associated .parkobj files with ObjectCreator in Windows, double-clicking them will always open a new instance. I think it would be better to add them into the same instance as new tabs. Or perhaps have a setting to control this behaviour under options.

**Comment by danielmeinert** [comment]
Yeah I want it to behave like that too and researched it already. Requires some more advanced registration of the app in windows. Eventually it should work like that, I don't know how high on the priority list I put it though. For now I'd recommend drag'n'dropping the files into the OC for opening them in the same instance.

**Comment by Richard-L** [comment]
Oh definitely low priority :)

**Comment by danielmeinert** [comment]
found a nice solution and seems to work. will be included in the next release
