### ISSUE TITLE
Change default preview colours to game standard red/yellow/brown

### ISSUE THREAD

**Issue by Richard-L** [danielmeinert/objectcreator#12]
The current object preview uses ORCT2's orange, magenta + whatever the tertiary preview colour is.

Inside the game however, you will see vanilla's red/yellow/brown standard, that (thankfully) is also still present in ORCT2 (in-game).

Think it would be nice to apply that for the object creator as well, to maintain stronger familiarity for the user.

Can you access the colours it uses for the preview?

Edit: I suppose you might be using `sprite exportall` (iir the commands correctly) from ORCT2. I guess that means the object editor is currently dependent on the game installed? If so, maybe another motivator to extract the sprites yourself and in the correct colours :)

**Comment by danielmeinert** [comment]
Here you can change the color in which the remap should be displayed. I can create a setting such that by default some color is selected for all objects that you open. For what it's worth, for object making purposes there is a good reason that the first remap is not one of the available colors.

![grafik](https://github.com/danielmeinert/objectcreator/assets/39702411/73d0b084-cd15-4f33-af52-b62a579ae5d1)

**Comment by Richard-L** [comment]
Actually if you'd elaborate, I'd love to know this. How come the default ORCT2 colours are the orange magenta (+ what is the tertiary?)?

Also, vanilla RCT2 objects also used to apply this green magenta (+tertiary), didn't they?

![Screenshot_20230814-165145.png](https://github.com/danielmeinert/objectcreator/assets/4934209/c3ebfb1f-3fa1-4d12-9685-c7351d87e5ad)

Trigger mentioned to me it's "internal" to legacy DATs, and not typically something you could choose in the game.

**Comment by Richard-L** [comment]
Actually if you'd elaborate, I'd love to know this. How come the default ORCT2 colours are the orange magenta (+ what is the tertiary?)?

Also, vanilla RCT2 objects also used to apply this green magenta (+tertiary), didn't they?

![Screenshot_20230814-165145.png](https://github.com/danielmeinert/objectcreator/assets/4934209/c3ebfb1f-3fa1-4d12-9685-c7351d87e5ad)

Trigger mentioned to me it's "internal" to legacy DATs, and not typically something you could choose in the game.

**Comment by danielmeinert** [comment]
The sprites are saved in the dats as an indexed image. That means for each pixel it does not store the rgb value but just a number between 0 and 255. Then when an object is to be drawn the game uses a lookup table (the palette) to match every index with an RGB value. That is the reason why the palettes work easily in the game, you just change the look up table but not the sprites. 
Now, the first remap has indeces reserved for itself (I think its indices 1-13 but I'm not sure). However, those indices are not connected to any other ingame color appearing in the game. That's unlike the second remap, which is just the pink and the game changes the behaviour depending of if the flag for the second remap is set or not. Therefore, when editing objects, the first remap color pixels should appear in another color than the available pixels for the program to be able to distinguish between whether you want to use the remap or the actual color (not for example that on the contrary when the second remap flag is set, the sprite cannot have any pink in it).
Which color you use in the editor or outside the game to represent the 12 first remap colors is completely arbitrary as long as they get mapped when indexed to the correct values. The Open RCT team decided for the orange colors where in the old editor the green was used (not that this green is different from the ingame green).

**Comment by Richard-L** [comment]
Hmm, I read those lines a few times but not all of them are clear. I might look up some palettes and their colours to make this more visual for myself.
Just this: RCT1/2 is never RGB, always indexed colour.

On the main concern of the issue: do you agree the default preview should match the default preview of the game? I find ORCT2's external sprite extract colours very foreign, and the orange and magenta are also not different enough from one another.

**Comment by danielmeinert** [comment]
It should be up to the user. Currently, if you dislike the OpenRCT orange for first remap you can change it in the settings menu to the old object maker green. I'll add also an option for default selected preview colors.
