### ISSUE TITLE
LVMIST.DAT causes error trapper

### ISSUE THREAD

**Issue by autosysops** [danielmeinert/objectcreator#16]
error:
![image](https://github.com/danielmeinert/objectcreator/assets/96066335/843eb16f-5f66-4b82-98ef-57093c2cbe1a)

version 0.1.5

**Comment by danielmeinert** [comment]
There is an error in a length check in the dat-importer. I fixed it now and I think I will make an updated quick fix release cause it's essential for loading sprites lol

Thanks for the report!
