### ISSUE TITLE
Allow drag'n'drop opening of files

### ISSUE THREAD

**Issue by Richard-L** [danielmeinert/objectcreator#2]
Currently this is not possible but would be a welcome QoL improvement. Thanks for considering.

https://github.com/danielmeinert/objectcreator/assets/4934209/33825359-5349-4c30-99a4-33fa409d588e

**Comment by danielmeinert** [comment]
Implemented 

![Animation](https://github.com/danielmeinert/objectcreator/assets/39702411/7a4fd7eb-82e1-4adc-8f59-b986b9ba094a)
