### ISSUE TITLE
Opening small scenery parkobj file doesn't populate Cursor or Object ID

### ISSUE THREAD

**Issue by Xtreme97-RCT** [danielmeinert/objectcreator#25]
When opening a small scenery parkobj, all object data is pre-populated except for the cursor and Object ID.

The cursor is set as "CURSOR BLANK" upon opening, even if the object was saved with a specific cursor such as "CURSOR ARROW".

Similarly, the Object ID is cleared upon opening. This makes editing WIP objects difficult as it needs to be re-populated every time you open the object.

Steps to reproduce:
1. Save an object with the Cursor and Object ID filled in.
2. Close the Object Creator and re-open the program.
3. Open the object that was just saved.
4. Cursor and Object ID are not filled in.

Before saving:
![image](https://github.com/danielmeinert/objectcreator/assets/64152940/22add6a6-27cd-4761-8fae-9db36932d21e)

After re-opening object:
![image](https://github.com/danielmeinert/objectcreator/assets/64152940/caf1f8ca-3e70-463e-bc4e-03273285c711)

**Comment by danielmeinert** [comment]
fixed with v0.1.8
