### ISSUE TITLE
Add .parkobj support

### ISSUE THREAD

**Issue by Richard-L** [danielmeinert/objectcreator#6]
Not sure if this is within the intended scope of the project?

**Comment by danielmeinert** [comment]
The programm entirely runs with parkobj. Dats are imported, not the other way round.

**Comment by Richard-L** [comment]
You don't want to support the importing of parkobj? It feels like a very relevant thing going forward.

**Comment by danielmeinert** [comment]
What I meant is that internally everything is a parkobj. dat objects get converted internally into parkobj when loading. In fact you can only save as parkobj and of course already load parkobj as well as .json files (as in the 'official' OpenRCT objects).

**Comment by Richard-L** [comment]
Yeah I understand.

But if you wanted to use sprite content from an existing parkobj, you couldn't do that currently could you? You'd have to extra the object and manually import the sprites.

But even just to have data about a parkobj parsable outside of the game itself would be useful.

**Comment by Richard-L** [comment]
How do you load existing parkobj? 🤔

**Comment by danielmeinert** [comment]
Through the loading window. Of course it has to be a SS parkobj.

**Comment by Richard-L** [comment]
It only lets me load .DAT though. .PARKOBJ aren't even a filetype I can choose.
Unless I'm missing something.

**Comment by danielmeinert** [comment]
![grafik](https://github.com/danielmeinert/objectcreator/assets/39702411/305e2e83-c4b6-4ecf-9792-49f85630ab06)
 This is what shows me in the object load window. Can you post a screen of yours if it's different?

**Comment by Richard-L** [comment]
Thanks for getting back again. I think I had an accidental filter for DAT files only, probably due to an unlucky mousewheel at some point.

Small scenery PARKOBJ work perfectly 👍
