### ISSUE TITLE
Make .parkobj associations optional

### ISSUE THREAD

**Issue by Richard-L** [danielmeinert/objectcreator#9]
The new installer seems to have associated .parkobj files within Windows:
![image](https://github.com/danielmeinert/objectcreator/assets/4934209/210c4a27-724d-4e40-b994-0fb708affcc3)

I don't recall there being an option for this in the installer. I would have preferred to not have this association.

**Comment by danielmeinert** [comment]
will be done with the next release 👍

**Comment by Richard-L** [comment]
Nice. But why close this then? 😅
